name: CI Pipeline

on:
  push:
    branches: [ "production" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      
    - name: Build the Docker image
      run: docker build -t minhduyyy/certx-space .
    - name: Push to Dockerhub
      run: docker push minhduyyy/certx-space:latest